const FLAGS: Record<string, string> = {
  // CONCACAF
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Costa Rica": "🇨🇷",
  "Panama": "🇵🇦",
  "Honduras": "🇭🇳",
  "Jamaica": "🇯🇲",
  "Haiti": "🇭🇹",
  "Curaçao": "🇨🇼",
  "Curacao": "🇨🇼",
  "El Salvador": "🇸🇻",
  "Guatemala": "🇬🇹",
  "Trinidad and Tobago": "🇹🇹",

  // CONMEBOL
  "Argentina": "🇦🇷",
  "Brazil": "🇧🇷",
  "Uruguay": "🇺🇾",
  "Colombia": "🇨🇴",
  "Ecuador": "🇪🇨",
  "Peru": "🇵🇪",
  "Chile": "🇨🇱",
  "Paraguay": "🇵🇾",
  "Venezuela": "🇻🇪",
  "Bolivia": "🇧🇴",

  // UEFA
  "France": "🇫🇷",
  "Spain": "🇪🇸",
  "Germany": "🇩🇪",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Portugal": "🇵🇹",
  "Netherlands": "🇳🇱",
  "Italy": "🇮🇹",
  "Belgium": "🇧🇪",
  "Croatia": "🇭🇷",
  "Switzerland": "🇨🇭",
  "Denmark": "🇩🇰",
  "Poland": "🇵🇱",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Austria": "🇦🇹",
  "Czechia": "🇨🇿",
  "Czech Republic": "🇨🇿",
  "Hungary": "🇭🇺",
  "Turkey": "🇹🇷",
  "Türkiye": "🇹🇷",
  "Ukraine": "🇺🇦",
  "Serbia": "🇷🇸",
  "Romania": "🇷🇴",
  "Greece": "🇬🇷",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Republic of Ireland": "🇮🇪",
  "Ireland": "🇮🇪",
  "Northern Ireland": "🏴󠁧󠁢󠁮󠁩󠁲󠁿",
  "Iceland": "🇮🇸",
  "Finland": "🇫🇮",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Albania": "🇦🇱",
  "North Macedonia": "🇲🇰",
  "Bosnia-Herzegovina": "🇧🇦",
  "Bosnia and Herzegovina": "🇧🇦",

  // AFC
  "Japan": "🇯🇵",
  "South Korea": "🇰🇷",
  "Korea Republic": "🇰🇷",
  "Australia": "🇦🇺",
  "Iran": "🇮🇷",
  "Saudi Arabia": "🇸🇦",
  "Qatar": "🇶🇦",
  "Iraq": "🇮🇶",
  "United Arab Emirates": "🇦🇪",
  "UAE": "🇦🇪",
  "Oman": "🇴🇲",
  "China": "🇨🇳",
  "China PR": "🇨🇳",
  "Vietnam": "🇻🇳",
  "Thailand": "🇹🇭",
  "Uzbekistan": "🇺🇿",
  "Jordan": "🇯🇴",
  "Lebanon": "🇱🇧",

  // CAF
  "Senegal": "🇸🇳",
  "Morocco": "🇲🇦",
  "Tunisia": "🇹🇳",
  "Algeria": "🇩🇿",
  "Egypt": "🇪🇬",
  "Nigeria": "🇳🇬",
  "Ghana": "🇬🇭",
  "Cameroon": "🇨🇲",
  "Ivory Coast": "🇨🇮",
  "Côte d'Ivoire": "🇨🇮",
  "Cote d'Ivoire": "🇨🇮",
  "South Africa": "🇿🇦",
  "Mali": "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "DR Congo": "🇨🇩",
  "Congo DR": "🇨🇩",

  // OFC
  "New Zealand": "🇳🇿",
  "Fiji": "🇫🇯",

  // Other
  "Israel": "🇮🇱",
};

export function flagFor(team: string): string {
  if (!team || team === "TBD") return "";
  return FLAGS[team] ?? "";
}
