/** Maps team name → ISO 3166-1 alpha-2 code (lowercase) for flagcdn.com */
const CODES: Record<string, string> = {
  // CONCACAF
  "Canada":                  "ca",
  "Mexico":                  "mx",
  "United States":           "us",
  "USA":                     "us",
  "Costa Rica":              "cr",
  "Panama":                  "pa",
  "Honduras":                "hn",
  "Jamaica":                 "jm",
  "Haiti":                   "ht",
  "Curaçao":                 "cw",
  "Curacao":                 "cw",
  "El Salvador":             "sv",
  "Guatemala":               "gt",
  "Trinidad and Tobago":     "tt",

  // CONMEBOL
  "Argentina":               "ar",
  "Brazil":                  "br",
  "Uruguay":                 "uy",
  "Colombia":                "co",
  "Ecuador":                 "ec",
  "Peru":                    "pe",
  "Chile":                   "cl",
  "Paraguay":                "py",
  "Venezuela":               "ve",
  "Bolivia":                 "bo",

  // UEFA
  "France":                  "fr",
  "Spain":                   "es",
  "Germany":                 "de",
  "England":                 "gb-eng",  // flagcdn subdiv code
  "Portugal":                "pt",
  "Netherlands":             "nl",
  "Italy":                   "it",
  "Belgium":                 "be",
  "Croatia":                 "hr",
  "Switzerland":             "ch",
  "Denmark":                 "dk",
  "Poland":                  "pl",
  "Sweden":                  "se",
  "Norway":                  "no",
  "Austria":                 "at",
  "Czechia":                 "cz",
  "Czech Republic":          "cz",
  "Hungary":                 "hu",
  "Turkey":                  "tr",
  "Türkiye":                 "tr",
  "Ukraine":                 "ua",
  "Serbia":                  "rs",
  "Romania":                 "ro",
  "Greece":                  "gr",
  "Wales":                   "gb-wls",
  "Scotland":                "gb-sct",
  "Republic of Ireland":     "ie",
  "Ireland":                 "ie",
  "Northern Ireland":        "gb-nir",
  "Iceland":                 "is",
  "Finland":                 "fi",
  "Slovakia":                "sk",
  "Slovenia":                "si",
  "Albania":                 "al",
  "North Macedonia":         "mk",
  "Macedonia":               "mk",
  "Bosnia-Herzegovina":      "ba",
  "Bosnia and Herzegovina":  "ba",
  "Bosnia & Herzegovina":    "ba",
  "Kosovo":                  "xk",
  "Georgia":                 "ge",
  "Armenia":                 "am",
  "Azerbaijan":              "az",
  "Luxembourg":              "lu",
  "Bulgaria":                "bg",
  "Cyprus":                  "cy",
  "Estonia":                 "ee",
  "Latvia":                  "lv",
  "Lithuania":               "lt",
  "Belarus":                 "by",
  "Moldova":                 "md",
  "Montenegro":              "me",
  "Malta":                   "mt",

  // AFC
  "Japan":                   "jp",
  "South Korea":             "kr",
  "Korea Republic":          "kr",
  "Korea":                   "kr",
  "Australia":               "au",
  "Iran":                    "ir",
  "Saudi Arabia":            "sa",
  "Qatar":                   "qa",
  "Iraq":                    "iq",
  "United Arab Emirates":    "ae",
  "UAE":                     "ae",
  "Oman":                    "om",
  "China":                   "cn",
  "China PR":                "cn",
  "Vietnam":                 "vn",
  "Thailand":                "th",
  "Uzbekistan":              "uz",
  "Jordan":                  "jo",
  "Lebanon":                 "lb",
  "Bahrain":                 "bh",
  "Kuwait":                  "kw",
  "Palestine":               "ps",
  "State of Palestine":      "ps",
  "Kyrgyzstan":              "kg",
  "Tajikistan":              "tj",
  "Syria":                   "sy",
  "Indonesia":               "id",
  "India":                   "in",
  "Philippines":             "ph",

  // CAF
  "Senegal":                 "sn",
  "Morocco":                 "ma",
  "Tunisia":                 "tn",
  "Algeria":                 "dz",
  "Egypt":                   "eg",
  "Nigeria":                 "ng",
  "Ghana":                   "gh",
  "Cameroon":                "cm",
  "Ivory Coast":             "ci",
  "Côte d'Ivoire":           "ci",
  "Cote d'Ivoire":           "ci",
  "South Africa":            "za",
  "Mali":                    "ml",
  "Burkina Faso":            "bf",
  "DR Congo":                "cd",
  "Congo DR":                "cd",
  "Democratic Republic of Congo": "cd",
  "Angola":                  "ao",
  "Kenya":                   "ke",
  "Zimbabwe":                "zw",
  "Tanzania":                "tz",
  "Uganda":                  "ug",
  "Zambia":                  "zm",
  "Cape Verde":              "cv",
  "Cabo Verde":              "cv",
  "Mauritania":              "mr",
  "Guinea":                  "gn",
  "Gabon":                   "ga",
  "Mozambique":              "mz",
  "Namibia":                 "na",
  "Equatorial Guinea":       "gq",
  "Comoros":                 "km",
  "Benin":                   "bj",
  "Niger":                   "ne",
  "Libya":                   "ly",
  "Sudan":                   "sd",

  // OFC
  "New Zealand":             "nz",
  "Fiji":                    "fj",

  // Other
  "Israel":                  "il",
};

/** Returns the ISO 3166-1 alpha-2 code (lowercase) for a given team name, or null. */
export function flagCodeFor(team: string): string | null {
  if (!team || team === "TBD") return null;
  return CODES[team] ?? null;
}

/**
 * @deprecated Use the <Flag> component instead (works on Windows Chrome).
 * Kept for any remaining call-sites that haven't been migrated.
 */
export function flagFor(_team: string): string {
  return "";
}
